name: C2ME Build Script

on:
  push: {}
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 22
        java-package: jdk

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18.1.8"

    - name: Install required dependencies
      run: sudo apt update && sudo apt install libtinfo5

    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle4-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle4-
        
    - name: Build C2ME
      run: |
        ./gradlew clean build --stacktrace

    - name: upload to modrinth and curseforge
      run: ./gradlew modrinth curseforge
      if: github.ref == 'refs/heads/dev/1.21.5'
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_UPLOAD_TOKEN }}
        CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
        GITHUB_EVENT_RAW_PATH: ${{ github.event_path }}
      continue-on-error: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: c2me-artifact
        path: 'build/libs/*.jar'
      
